# Generated by Django 3.2.9 on 2022-07-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_auth', '0002_user_is_verification_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_import_creation',
            field=models.BooleanField(default=False),
        ),
    ]
