# Generated by Django 3.2.9 on 2022-07-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_category', models.CharField(choices=[('About my clinic', 'About my clinic'), ('じぶんクリニックについて', 'じぶんクリニックについて'), ('How to use the site/services', 'How to use the site/services'), ('サイト・サービスの利用方法', 'サイト・サービスの利用方法'), ('Inquiries regarding registration and login', 'Inquiries regarding registration and login'), ('登録やログインに関するお問いわせ', '登録やログインに関するお問いわせ'), ('Other inquiries', 'Other inquiries'), ('その他のお問い合わせ', 'その他のお問い合わせ')], default='Other inquiries', max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('contents_of_inquiry', models.TextField(max_length=100)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_messages', to='inquiry.inquiry')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
