# Generated by Django 3.2.9 on 2022-07-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='inquirymessage',
            options={'ordering': ['-updated_at']},
        ),
    ]
