# Generated by Django 3.2.9 on 2022-07-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0002_auto_20220708_1912'),
        ('inquiry', '0002_auto_20220709_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_inquiries', to='drugstore.drugstore'),
        ),
    ]
