# Generated by Django 3.2.9 on 2022-07-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_rename_inquiry_pharmacist_inquiry_inquiry_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='contact_category',
            field=models.CharField(choices=[('About my clinic', 'About my clinic'), ('じぶんクリニックについて', 'じぶんクリニックについて'), ('How to use the site/services', 'How to use the site/services'), ('サイト・サービスの利用方法', 'サイト・サービスの利用方法'), ('Inquiries regarding registration and login', 'Inquiries regarding registration and login'), ('登録やログインに関するお問いわせ', '登録やログインに関するお問いわせ'), ('Inquiries regarding Password Reset', 'Inquiries regarding Password Reset'), ('パスワードリセットに関するお問い合わせ', 'パスワードリセットに関するお問い合わせ'), ('Other inquiries', 'Other inquiries'), ('その他のお問い合わせ', 'その他のお問い合わせ')], default='Other inquiries', max_length=50),
        ),
    ]
