# Generated by Django 3.2.9 on 2022-07-07 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('template', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_messages', to='reservation.forreservation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_sender_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMemoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_sender_message', to=settings.AUTH_USER_MODEL)),
                ('usermemo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memo_messages', to='reservation.usermemo')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateReservationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_template', to='message.reservationmessage')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='template_message', to='template.template')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
