# Generated by Django 3.2.9 on 2022-07-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationmessage',
            options={'ordering': ['updated_at']},
        ),
    ]
