# Generated by Django 3.2.9 on 2022-07-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_reservationmessage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatereservationmessage',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterModelOptions(
            name='usermemomessage',
            options={'ordering': ['updated_at']},
        ),
    ]
