# Generated by Django 3.2.9 on 2022-07-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20220711_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationmessage',
            name='is_seen_patient',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservationmessage',
            name='is_seen_pharmacy',
            field=models.BooleanField(default=True),
        ),
    ]
