# Generated by Django 3.2.9 on 2022-07-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_tips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinetips',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Medicine Tips', 'verbose_name_plural': 'Medicine Tips'},
        ),
    ]
