# Generated by Django 3.2.9 on 2022-07-07 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugstore', '0001_initial'),
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteDrugStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=0)),
                ('drugstore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drugstore.drugstore')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
