# Generated by Django 3.2.9 on 2022-07-07 10:59

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture_name_en', models.CharField(blank=True, max_length=200, null=True)),
                ('prefecture_name_jp', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugstore_name', models.CharField(blank=True, max_length=200, null=True)),
                ('handling_classification', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('prescription', 'prescription'), ('first drug', 'first drug'), ('second drug', 'second drug'), ('daily necessities', 'daily necessities'), ('food', 'food')], max_length=200), blank=True, null=True, size=None)),
                ('address', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(blank=True, max_length=100, null=True)),
                ('municipalities', models.CharField(blank=True, max_length=100, null=True)),
                ('fax', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('is_linked', models.BooleanField(default=False)),
                ('business_hours', models.CharField(blank=True, max_length=500, null=True)),
                ('established', models.DateTimeField(blank=True, null=True)),
                ('time1_start', models.TimeField(blank=True, null=True)),
                ('time1_end', models.TimeField(blank=True, null=True)),
                ('time2_start', models.TimeField(blank=True, null=True)),
                ('time2_end', models.TimeField(blank=True, null=True)),
                ('telephone_number', models.CharField(max_length=500)),
                ('no_of_employee', models.IntegerField(blank=True, null=True)),
                ('line_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefectures', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugstore.prefecture')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Representative', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugstore_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
