# Generated by Django 3.2.9 on 2022-07-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugstore',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='drugstore',
            name='representative',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
