# Generated by Django 3.2.9 on 2022-07-11 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugstore', '0002_auto_20220708_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugstore',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drugstore_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
