# Generated by Django 3.2.9 on 2022-07-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0003_alter_drugstore_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefecture',
            options={'ordering': ['-prefecture_rank']},
        ),
        migrations.AddField(
            model_name='prefecture',
            name='prefecture_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
