# Generated by Django 3.2.9 on 2022-07-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0004_auto_20220713_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prefecture',
            options={'ordering': ['prefecture_rank']},
        ),
    ]
