# Generated by Django 3.2.9 on 2022-07-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDrugInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=100, unique=True)),
                ('drug_efficasy_classification', models.CharField(max_length=100)),
                ('effects', models.CharField(max_length=100)),
                ('effects_logic', models.CharField(choices=[('and', 'AND'), ('or', 'OR'), ('not', 'NOT')], max_length=5)),
                ('warning', models.CharField(max_length=100)),
                ('warning_logic', models.CharField(choices=[('and', 'AND'), ('or', 'OR'), ('not', 'NOT')], max_length=5)),
                ('contraindications', models.CharField(max_length=100)),
                ('contraindications_logic', models.CharField(choices=[('and', 'AND'), ('or', 'OR'), ('not', 'NOT')], max_length=5)),
                ('concomitant', models.CharField(max_length=100)),
                ('concomitant_logic', models.CharField(choices=[('and', 'AND'), ('or', 'OR'), ('not', 'NOT')], max_length=5)),
                ('inquiry_company_name', models.CharField(max_length=100)),
                ('start_update_date', models.DateField(auto_now_add=True)),
                ('end_updated_date', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
