# Generated by Django 3.2.9 on 2022-07-07 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('filter_category_en', models.CharField(blank=True, max_length=200, null=True)),
                ('filter_category_jpn', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50)),
                ('allergy_info', models.TextField(blank=True, null=True, verbose_name='Allergy information')),
                ('allergy_reactive', models.TextField(blank=True, null=True, verbose_name='Allergic reactive drug')),
                ('type', models.IntegerField(choices=[(1, 'Self'), (2, 'Spouse'), (3, 'Daughter'), (4, 'Son'), (5, 'Mom'), (6, 'Dad')], default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('key_matter_information', models.TextField(blank=True, null=True)),
                ('line_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.CharField(choices=[('in_use', 'In Use'), ('stopping', 'Stopping')], default='in_use', max_length=15)),
                ('is_linked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription_date', models.DateField(max_length=4)),
                ('time', models.TimeField(blank=True, null=True)),
                ('isRed', models.BooleanField(default=False)),
                ('insurer_number', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField(max_length=4)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=50)),
                ('medical_institution_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('prescribing_physician', models.CharField(max_length=50)),
                ('prescription_details', models.TextField()),
                ('change_to_generic_drugs', models.CharField(choices=[('possible', 'possible'), ('impossible', 'impossible')], default='possible', max_length=50)),
                ('number_of_split_dispensing', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=1)),
                ('prescription_image', models.ImageField(upload_to='patient/prescriptions/images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='patient.patient')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionReceiptReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='patient.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PatientInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_choices', models.IntegerField(blank=True, choices=[(1, 'Business health insurance card'), (2, 'National health insurance card')], null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='insurance')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('date_of_issuance', models.DateField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_qualification', models.DateField(blank=True, null=True)),
                ('name_of_head_of_household', models.CharField(blank=True, max_length=30, null=True)),
                ('office_name', models.CharField(blank=True, max_length=30, null=True)),
                ('insurance_number', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(blank=True, max_length=30, null=True)),
                ('insurer_name', models.CharField(blank=True, max_length=50, null=True)),
                ('insurer_location', models.CharField(blank=True, max_length=20, null=True)),
                ('underlying_disease', models.TextField(blank=True, null=True)),
                ('family_medical_institution', models.CharField(blank=True, max_length=30, null=True)),
                ('family_dispensing_pharmacy', models.CharField(blank=True, max_length=30, null=True)),
                ('pharmacist_in_charge', models.CharField(blank=True, max_length=30, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_insurance', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('text', models.TextField(max_length=20)),
                ('file', models.FileField(upload_to='patient/document/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=2000, null=True)),
                ('city', models.CharField(max_length=20)),
                ('prefecture', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='patient.patient')),
            ],
        ),
    ]
