# Generated by Django 3.2.9 on 2022-07-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0005_alter_prefecture_options'),
        ('patient', '0002_auto_20220709_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pharmacy_visited',
            field=models.ManyToManyField(blank=True, related_name='pharmacy_patients', to='drugstore.DrugStore'),
        ),
    ]
