# Generated by Django 3.2.9 on 2022-07-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_pharmacy_visited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='Prescription_date',
            new_name='prescription_date',
        ),
    ]
