# Generated by Django 3.2.9 on 2022-07-07 11:00

from django.db import migrations, models
import django.db.models.deletion
import notice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificeDeliveryChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_target_choice', models.IntegerField(blank=True, null=True)),
                ('delivery_target_en', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_target_jpn', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificeStatusChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_choice', models.IntegerField(blank=True, null=True)),
                ('status_en', models.CharField(blank=True, max_length=50, null=True)),
                ('status_jpn', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image_registration', models.ImageField(blank=True, null=True, upload_to='notice/registration')),
                ('date', models.DateField(blank=True, null=True)),
                ('deliver_start_time', models.DateField(blank=True, null=True)),
                ('deliver_end_time', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_target', models.ForeignKey(default=notice.models.default_delivery, on_delete=django.db.models.deletion.DO_NOTHING, to='notice.notificedeliverychoices')),
                ('status', models.ForeignKey(default=notice.models.default_status, on_delete=django.db.models.deletion.DO_NOTHING, to='notice.notificestatuschoices')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ('-updated_at',),
            },
        ),
    ]
