# Generated by Django 3.2.9 on 2022-07-07 12:14

from django.db import migrations, models
import django.db.models.deletion
import notice.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='status',
            field=models.ForeignKey(blank=True, default=notice.models.default_status, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notice.notificestatuschoices'),
        ),
    ]
