# Generated by Django 3.2.9 on 2022-07-10 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaceutical_manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmaceuticalmanufacturer',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='pharmaceuticalmanufacturer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmaceuticalmanufacturer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
