# Generated by Django 3.2.9 on 2022-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220709_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermemo',
            name='is_usermemo_added',
            field=models.BooleanField(default=False),
        ),
    ]
